# fly.toml app configuration file generated for ota-py on 2024-01-20T19:16:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ota-py"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
